/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.mif.manager.vista;

import java.util.List;
import javax.swing.ButtonModel;
import org.mif.manager.model.Categoria;
import org.mif.manager.model.Equip;

/**
 *
 * @author marks
 */
public class AfegirEquipFrame extends javax.swing.JFrame {

    /**
     * Creates new form AfegirEquipFrame
     */
    public AfegirEquipFrame() {
        initComponents();
        carregarCategories();
        // Afegim els bottons al grup de bottons manualment, no se fer-ho des-de el design:
        femeniRButton.setActionCommand("femeni");
        grupSelTipus.add(femeniRButton);
        mixteRButton.setActionCommand("mixte");
        grupSelTipus.add(mixteRButton);
        masculiRButton.setActionCommand("masculi");
        grupSelTipus.add(masculiRButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupSelTipus = new javax.swing.ButtonGroup();
        enrereButton = new javax.swing.JButton();
        femeniRButton = new javax.swing.JRadioButton();
        mixteRButton = new javax.swing.JRadioButton();
        masculiRButton = new javax.swing.JRadioButton();
        afegirButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomTextField = new javax.swing.JTextField();
        categComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Afegir Equip Nou");
        setResizable(false);

        enrereButton.setText("<");
        enrereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrereButtonActionPerformed(evt);
            }
        });

        femeniRButton.setText("Femení");

        mixteRButton.setText("Mixte");

        masculiRButton.setText("Masculí");

        afegirButton.setBackground(new java.awt.Color(0, 102, 0));
        afegirButton.setForeground(new java.awt.Color(255, 255, 255));
        afegirButton.setText("Afegir");
        afegirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipus:");

        jLabel2.setText("Nom de l'equip:");

        jLabel3.setText("Categoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enrereButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(categComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masculiRButton)
                            .addComponent(mixteRButton)
                            .addComponent(femeniRButton)
                            .addComponent(jLabel1))
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(afegirButton)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enrereButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femeniRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mixteRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(masculiRButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(afegirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afegirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirButtonActionPerformed
        Equip nouEquip = new Equip();
        // Per poder obtenir quin radiobutton es troba seleccionat (o si no hi és cap) m'he guiat amb les respostes d'aquesta pregunta: https://stackoverflow.com/questions/201287/how-do-i-get-which-jradiobutton-is-selected-from-a-buttongroup
        ButtonModel seleccionat = grupSelTipus.getSelection();

        if (seleccionat != null)
        {
            String tipus = seleccionat.getActionCommand();
            
            switch (tipus)
            {
                case "femeni":
                    nouEquip.setTipus("D");
                    break;
                    
                case "mixte":
                    nouEquip.setTipus("M");
                    break;
                    
                case "masculi":
                    nouEquip.setTipus("H");
                    break;
            }
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Has de seleccionar un Tipus!", "Error de Tipus", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!nomTextField.getText().isBlank())
        {
            nouEquip.setNom(nomTextField.getText());
        }
        else 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Has de introduir un nom al equip!", "Error de Nom", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // No cal fer comprovacions ja que el comboBox te preseleccionada una categoria, i no es pot no seleccionar ninguna
        nouEquip.setCategoria((Categoria) categComboBox.getSelectedItem());
        nouEquip.setTemporada(Utils.getTemporadaActual().getAnny());
        
        try 
        {
            Utils.getGBD().afegirEquip(nouEquip);
        }
        catch (Exception ex)
        {
            javax.swing.JOptionPane.showMessageDialog(this, ex, "Error d'inserció!", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Utils.setEquips(Utils.getTemporadaActual());
        GestEquipsFrame equipsFrame = new GestEquipsFrame();
        equipsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_afegirButtonActionPerformed

    private void enrereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrereButtonActionPerformed
        GestEquipsFrame equipsFrame = new GestEquipsFrame();
        equipsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_enrereButtonActionPerformed

    private void carregarCategories()
    {
        if (Utils.getCategories().isEmpty())
        {
            Utils.setCategories();
        }
        
        List<Categoria> cats = Utils.getCategories();
        
        for (Categoria cat : cats)
        {
            categComboBox.addItem(cat);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegirButton;
    private javax.swing.JComboBox<Categoria> categComboBox;
    private javax.swing.JButton enrereButton;
    private javax.swing.JRadioButton femeniRButton;
    private javax.swing.ButtonGroup grupSelTipus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton masculiRButton;
    private javax.swing.JRadioButton mixteRButton;
    private javax.swing.JTextField nomTextField;
    // End of variables declaration//GEN-END:variables
}
