/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.mif.manager.vista;

import org.mif.manager.model.Jugador;

/**
 *
 * @author marks
 */
public class AfegirEditJug extends javax.swing.JFrame {

    private Jugador jugadorEditant;
    
    /**
     * Creates new form AfegirEditJug
     */
    public AfegirEditJug(Jugador jug) {
        initComponents();
        
        sexeGrup.add(homeRadioButton);
        sexeGrup.add(donaRadioButton);
        
        this.jugadorEditant = jug;
        
        if (jug != null)
        {
             // Editar: omple camps
            nomTextField.setText(jug.getNom());
            cognomsTextField.setText(jug.getCognoms());
            nifTextField.setText(jug.getIdLegal());
            // Data naixement en format dd/MM/yyyy
            if (jug.getData_naix() != null)
            {
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
                naixTextField.setText(jug.getData_naix().format(formatter));
            }
            else
            {
                naixTextField.setText("");
            }
            // Sexe (assumint "H" o "D")
            if (jug.getSexe() != null)
            {
                if (jug.getSexe().equalsIgnoreCase("H"))
                {
                    homeRadioButton.setSelected(true);
                }
                else if (jug.getSexe().equalsIgnoreCase("D"))
                {
                    donaRadioButton.setSelected(true);
                }
            }
            else
            {
                // Cap seleccionat si null
                sexeGrup.clearSelection();
            }

            if (jug.getIban() != null)
            {
                ibanTextField.setText(jug.getIban());
            }
            else
            {
                ibanTextField.setText("");
            }

            if (jug.getAny_fi_revi_medica().getYear() > 0)
            {
                reviMedicaTextField.setText(String.valueOf(jug.getAny_fi_revi_medica().getYear()));
            }
            else
            { 
                reviMedicaTextField.setText("");
            }
            
            if (jug.getAdresa() != null)
            {
                adrecaTextField.setText(jug.getAdresa());
            }
            else
            {
                adrecaTextField.setText("");
            }
            
            naixTextField.setEditable(false);
            homeRadioButton.setEnabled(false);
            donaRadioButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexeGrup = new javax.swing.ButtonGroup();
        nomTextField = new javax.swing.JTextField();
        nomLabel = new javax.swing.JLabel();
        cognomsTextField = new javax.swing.JTextField();
        cognomsLabel = new javax.swing.JLabel();
        nifLabel = new javax.swing.JLabel();
        nifTextField = new javax.swing.JTextField();
        naixTextField = new javax.swing.JTextField();
        reviMedicaTextField = new javax.swing.JTextField();
        reviMedicaLabel = new javax.swing.JLabel();
        naixLabel = new javax.swing.JLabel();
        ibanLabel = new javax.swing.JLabel();
        ibanTextField = new javax.swing.JTextField();
        sexeLabel = new javax.swing.JLabel();
        homeRadioButton = new javax.swing.JRadioButton();
        donaRadioButton = new javax.swing.JRadioButton();
        adrecaLabel = new javax.swing.JLabel();
        adrecaTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        enrereButton = new javax.swing.JButton();
        errNomLabel = new javax.swing.JLabel();
        errCogLabel = new javax.swing.JLabel();
        errSexLabel = new javax.swing.JLabel();
        errNaixLabel = new javax.swing.JLabel();
        errReviMedLabel = new javax.swing.JLabel();
        errNifLabel = new javax.swing.JLabel();
        errIbanLabel = new javax.swing.JLabel();
        errAdrLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        nomLabel.setText("Nom:");

        cognomsLabel.setText("Cognoms:");

        nifLabel.setText("NIF:");

        reviMedicaLabel.setText("Any fi de la revisió mèdica (ex: 2028):");

        naixLabel.setText("Data de naixement (dd/mm/yyyy):");

        ibanLabel.setText("IBAN:");

        sexeLabel.setText("Sexe:");

        homeRadioButton.setText("H");

        donaRadioButton.setText("D");

        adrecaLabel.setText("Adreça (Separat per \",\" carrer i numero, codi postal i població):");

        guardarButton.setBackground(new java.awt.Color(51, 102, 0));
        guardarButton.setForeground(new java.awt.Color(255, 255, 255));
        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        enrereButton.setText("<");
        enrereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrereButtonActionPerformed(evt);
            }
        });

        errNomLabel.setForeground(new java.awt.Color(153, 0, 0));
        errNomLabel.setPreferredSize(new java.awt.Dimension(160, 0));

        errCogLabel.setForeground(new java.awt.Color(153, 0, 0));
        errCogLabel.setPreferredSize(new java.awt.Dimension(160, 0));

        errSexLabel.setForeground(new java.awt.Color(153, 0, 0));
        errSexLabel.setPreferredSize(new java.awt.Dimension(160, 0));

        errNaixLabel.setForeground(new java.awt.Color(153, 0, 0));
        errNaixLabel.setPreferredSize(new java.awt.Dimension(160, 0));

        errReviMedLabel.setForeground(new java.awt.Color(153, 0, 0));
        errReviMedLabel.setPreferredSize(new java.awt.Dimension(160, 0));

        errNifLabel.setForeground(new java.awt.Color(153, 0, 0));
        errNifLabel.setPreferredSize(new java.awt.Dimension(160, 0));

        errIbanLabel.setForeground(new java.awt.Color(153, 0, 0));
        errIbanLabel.setPreferredSize(new java.awt.Dimension(200, 0));

        errAdrLabel.setForeground(new java.awt.Color(153, 0, 0));
        errAdrLabel.setPreferredSize(new java.awt.Dimension(160, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ibanTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adrecaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(errAdrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(adrecaTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nomLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(errNomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cognomsLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(errCogLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cognomsTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nifLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(errNifLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(nifTextField)
                                    .addComponent(nomTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ibanLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(errIbanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errReviMedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(errNaixLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reviMedicaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(naixLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(naixTextField)
                                        .addComponent(reviMedicaTextField)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(homeRadioButton)
                                                .addComponent(sexeLabel))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(donaRadioButton)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(errSexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enrereButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enrereButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomLabel)
                        .addComponent(sexeLabel)
                        .addComponent(errSexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errNomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeRadioButton)
                    .addComponent(donaRadioButton))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errCogLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cognomsLabel)
                        .addComponent(naixLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cognomsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(errNaixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nifLabel)
                    .addComponent(reviMedicaLabel)
                    .addComponent(errNifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reviMedicaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ibanLabel)
                            .addComponent(errIbanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(errReviMedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ibanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adrecaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errAdrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adrecaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // Buidem errors
        errNomLabel.setText("");
        errCogLabel.setText("");
        errSexLabel.setText("");
        errNaixLabel.setText("");
        errNifLabel.setText("");
        errIbanLabel.setText("");
        errAdrLabel.setText("");
        errReviMedLabel.setText("");

        boolean hasError = false;

        String nom = nomTextField.getText().trim();
        String cognoms = cognomsTextField.getText().trim();
        String nif = nifTextField.getText().trim();
        String dataNaixStr = naixTextField.getText().trim();
        
        String sexe = null;
        if (homeRadioButton.isSelected())
        { 
            sexe = "H"; 
        }
        else if (donaRadioButton.isSelected()) 
        { 
            sexe = "D"; 
        }
        
        String iban = ibanTextField.getText().trim();
        String adreca = adrecaTextField.getText().trim();
        String anyFiReviMedStr = reviMedicaTextField.getText().trim();

        // VALIDACIÓ: només es poden modificar sexe/dataNaix si és un nou jugador!
        if (jugadorEditant != null) {
            dataNaixStr = ""; // No permetre editar
            sexe = null;
        }

        // Validem els camps de manera bàsica
        if (nom.isEmpty())
        { 
            errNomLabel.setText("Nom obligatori."); 
            hasError = true; 
        }
        if (cognoms.isEmpty())
        { 
            errCogLabel.setText("Cognoms obligatoris."); 
            hasError = true; 
        }
        if (nif.isEmpty())
        { 
            errNifLabel.setText("NIF obligatori."); 
            hasError = true; 
        }
        // Només demanem data naixement i sexe si és un nou jugador
        if (jugadorEditant == null)
        {
            if (sexe == null)
            { 
                errSexLabel.setText("Selecciona sexe."); 
                hasError = true; 
            }
            if (dataNaixStr.isEmpty())
            { 
                errNaixLabel.setText("La data de naixement és obligatòria."); 
                hasError = true; 
            }
        }
        if (iban.isEmpty())
        { 
            errIbanLabel.setText("IBAN obligatori."); 
            hasError = true; 
        }
        if (adreca.isEmpty())
        { 
            errAdrLabel.setText("Adreça obligatòria."); 
            hasError = true; 
        }

        // Validació d'IBAN
        String ibanClean = iban.replaceAll("\\s", "");
        if (!ibanClean.matches("^ES\\d{22}$"))
        {
            errIbanLabel.setText("Format incorrecte.");
            hasError = true;
        }

        // Validació d’adreça (visual)
        if (!adreca.isEmpty() && adreca.chars().filter(ch -> ch == ',').count() < 2)
        {
            errAdrLabel.setText("Format incorrecte");
            hasError = true;
        }

        // Validació de “Any fi revisió” (visual)
        java.time.LocalDate anyFiReviMedica = null;
        if (!anyFiReviMedStr.isEmpty())
        {
            if (!anyFiReviMedStr.matches("^\\d{4}$"))
            {
                errReviMedLabel.setText("Han de ser 4 xifres.");
                hasError = true;
            }
            else
            {
                int any = Integer.parseInt(anyFiReviMedStr);
                int anyActual = java.time.LocalDate.now().getYear();
                if (any <= anyActual)
                {
                    errReviMedLabel.setText("Ha de ser un any futur.");
                    hasError = true;
                } 
                else 
                {
                    anyFiReviMedica = java.time.LocalDate.of(any, 1, 1);
                }
            }
        }

        // Validació de data naixement (només si és nou)
        java.time.LocalDate dataNaix = null;
        if (jugadorEditant == null && !dataNaixStr.isEmpty()) 
        {
            try 
            {
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
                dataNaix = java.time.LocalDate.parse(dataNaixStr, formatter);
            } 
            catch (Exception ex) 
            {
                errNaixLabel.setText("Format ha de ser dd/mm/yyyy");
                hasError = true;
            }
        }

        if (hasError) { return; }

        try
        {
            Jugador jug;
            if (jugadorEditant == null) { jug = new Jugador(); }
            else { jug = jugadorEditant; }

            jug.setNom(nom);
            jug.setCognoms(cognoms);
            jug.setIdLegal(nif);
            jug.setIban(ibanClean);
            jug.setAdresa(adreca);
            if (anyFiReviMedica != null) 
            { 
                jug.setAny_fi_revi_medica(anyFiReviMedica); 
            }
            else 
            {
                jug.setAny_fi_revi_medica(null); 
            }
            // Només per crear nou jugador
            if (jugadorEditant == null) 
            {
                jug.setSexe(sexe);
                jug.setData_naix(dataNaix);
            }

            boolean esNou = (jugadorEditant == null);
            String error = Utils.guardarJugador(jug, esNou);
            if (error != null) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "No s'ha pogut desar el jugador: " + error, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            GestJugsFrame frame = new GestJugsFrame();
            frame.setVisible(true);
            this.dispose();
        }
        catch (RuntimeException ex) 
        {
            // Si l'error es diferent dels que controlem aqui, comprovem els missatges que retorna el model de jugador
            String msg = ex.getMessage();
            if (msg.contains("Nom")) { errNomLabel.setText(msg); }
            else if (msg.contains("Cognoms")) { errCogLabel.setText(msg); }
            else if (msg.contains("Sexe")) { errSexLabel.setText(msg); }
            else if (msg.contains("no futura")) { errNaixLabel.setText(msg); }
            else if (msg.contains("Format")) { errNifLabel.setText(msg); }
            else if (msg.contains("IBAN")) { errIbanLabel.setText("Format incorrecte."); }
            else if (msg.contains("adreça")) { errAdrLabel.setText("Format incorrecte."); }
            else if (msg.contains("Data")) { errReviMedLabel.setText("Any futur obligatori"); }
            else { javax.swing.JOptionPane.showMessageDialog(this, msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE); }
        }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void enrereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrereButtonActionPerformed
        GestJugsFrame jugsFrame = new GestJugsFrame();
        jugsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_enrereButtonActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adrecaLabel;
    private javax.swing.JTextField adrecaTextField;
    private javax.swing.JLabel cognomsLabel;
    private javax.swing.JTextField cognomsTextField;
    private javax.swing.JRadioButton donaRadioButton;
    private javax.swing.JButton enrereButton;
    private javax.swing.JLabel errAdrLabel;
    private javax.swing.JLabel errCogLabel;
    private javax.swing.JLabel errIbanLabel;
    private javax.swing.JLabel errNaixLabel;
    private javax.swing.JLabel errNifLabel;
    private javax.swing.JLabel errNomLabel;
    private javax.swing.JLabel errReviMedLabel;
    private javax.swing.JLabel errSexLabel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JRadioButton homeRadioButton;
    private javax.swing.JLabel ibanLabel;
    private javax.swing.JTextField ibanTextField;
    private javax.swing.JLabel naixLabel;
    private javax.swing.JTextField naixTextField;
    private javax.swing.JLabel nifLabel;
    private javax.swing.JTextField nifTextField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JLabel reviMedicaLabel;
    private javax.swing.JTextField reviMedicaTextField;
    private javax.swing.ButtonGroup sexeGrup;
    private javax.swing.JLabel sexeLabel;
    // End of variables declaration//GEN-END:variables
}
