/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.mif.manager.vista;

import java.util.List;
import javax.swing.DefaultListModel;
import org.mif.manager.model.Equip;
import org.mif.manager.model.Jugador;

/**
 *
 * @author marks
 */
public class SelGestioFrame extends javax.swing.JFrame
{
    private DefaultListModel<Equip> equipsListModel = new DefaultListModel<>();
    private DefaultListModel<Jugador> jugadorsListModel = new DefaultListModel<>();
    
    /**
     * Idea per gestionar les llistes treta de:
     * https://stackoverflow.com/questions/8176965/how-to-add-element-to-existing-jlist
     */
    public SelGestioFrame()
    {
        initComponents();
        equipsList.setModel(equipsListModel);
        jugadorList.setModel(jugadorsListModel);
        carregarLlistes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jugadorList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        equipsList = new javax.swing.JList<>();
        infoGestio = new javax.swing.JLabel();
        gestJugsButton = new javax.swing.JButton();
        gestEquipButton1 = new javax.swing.JButton();
        enrereButton = new javax.swing.JButton();
        jugadorsLabel = new javax.swing.JLabel();
        equipsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escollir Gestió");
        setResizable(false);

        jugadorList.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugadors"));
        jugadorList.setFocusable(false);
        jScrollPane1.setViewportView(jugadorList);

        equipsList.setBorder(javax.swing.BorderFactory.createTitledBorder("Equips"));
        equipsList.setFocusable(false);
        jScrollPane2.setViewportView(equipsList);

        infoGestio.setText("Mostrant equips i jugadors de la "+ Utils.getTemporadaActual());

        gestJugsButton.setText("Gestionar Jugadors");
        gestJugsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestJugsButtonActionPerformed(evt);
            }
        });

        gestEquipButton1.setText("Gestionar Equips");
        gestEquipButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestEquipButton1ActionPerformed(evt);
            }
        });

        enrereButton.setText("<");
        enrereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrereButtonActionPerformed(evt);
            }
        });

        jugadorsLabel.setForeground(new java.awt.Color(255, 0, 0));

        equipsLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(gestEquipButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gestJugsButton)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enrereButton)
                        .addGap(118, 118, 118)
                        .addComponent(infoGestio)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addComponent(equipsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jugadorsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrereButton)
                    .addComponent(infoGestio))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jugadorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gestEquipButton1)
                    .addComponent(gestJugsButton))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrereButtonActionPerformed
        SelTempFrame tempsFrame = new SelTempFrame();
        tempsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_enrereButtonActionPerformed

    private void gestEquipButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestEquipButton1ActionPerformed
        GestEquipsFrame equipsFrame = new GestEquipsFrame();
        equipsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestEquipButton1ActionPerformed

    private void gestJugsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestJugsButtonActionPerformed
        GestJugsFrame jugsFrame = new GestJugsFrame();
        jugsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestJugsButtonActionPerformed

    /**
     * Funció per carregar les llistes d'equips i jugadors que fan de vista prèvia
     */
    private void carregarLlistes()
    {
        List<Equip> equips = Utils.obtenirEquips(Utils.getTemporadaActual());
        List<Jugador> jugadors = Utils.obtenirJugadors();

        System.out.println(equips.toString());
        
        if (equips.isEmpty())
        {
            equipsLabel.setText("No hi han equips aquesta temporada");
        }
        
        if (jugadors.isEmpty())
        {
            jugadorsLabel.setText("No hi han jugadors a la bd");
        }

        for (Equip equip : equips)
        {
            equipsListModel.addElement(equip);
        }
        
        for (Jugador jugador : jugadors)
        {
            jugadorsListModel.addElement(jugador);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelGestioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelGestioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelGestioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelGestioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelGestioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrereButton;
    private javax.swing.JLabel equipsLabel;
    private javax.swing.JList<Equip> equipsList;
    private javax.swing.JButton gestEquipButton1;
    private javax.swing.JButton gestJugsButton;
    private javax.swing.JLabel infoGestio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Jugador> jugadorList;
    private javax.swing.JLabel jugadorsLabel;
    // End of variables declaration//GEN-END:variables
}
